# Generated by Django 4.2.2 on 2023-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('instrument', models.CharField(default='', max_length=50, verbose_name='악기')),
                ('link', models.CharField(max_length=150, verbose_name='링크')),
                ('body', models.TextField(default='', verbose_name='자기소개 및 지원동기')),
            ],
        ),
    ]
